### ISSUE TITLE
Quick Question.

### ISSUE THREAD

**Issue by TheOnlyOneLeft** [OliverBoy/Luna#3]
I was wondering if you could tell me how to setup the games, make my server available to everyone on my local network*, and tell me how to make Luna use the mediaservers assets such as music per room, games, crumbs, and rooms. I am unable to find much information on the web.
*Whenever people try to join on my local network they get the login page but when attempting to login they get a blue screen.

**Comment by OliverBoy** [comment]
You can use games on luna, I'd recommend KitSune.
